### ISSUE TITLE
June firmware file is broken

### ISSUE THREAD

**Issue by Knives79** [AirReps/firmware#1]
Hi, I tried download the June firmware file, but inside the zip all the names are messy.
![Immagine_2021-07-23_104513](https://user-images.githubusercontent.com/46047656/127124975-2bac4d46-6f33-4731-9004-4660dec67ea2.jpg)

**Comment by johnnyvipcn2** [comment]
160 164 is available?

**Comment by wavpro** [comment]
> Hi, I tried download the June firmware file, but inside the zip all the names are messy.
> ![Immagine_2021-07-23_104513](https://user-images.githubusercontent.com/46047656/127124975-2bac4d46-6f33-4731-9004-4660dec67ea2.jpg)

The issue has been fixed and the correct files are now used.
