### ISSUE TITLE
I find a NEW firmware

### ISSUE THREAD

**Issue by JuneCN** [AirReps/firmware#3]
Hello ,I am Chinese user ,and I can not use English very well.

I had buy a FAKE AirPods Pro in Sep 30th , it's Airoha AB1562f chip, the company name is S32_cc pro，the firmware is 130.2.1.5 , the release date is Sep 21st 2021  ,the flash is 2M. I get these messages via Airoha SDK UT V0.0.0.2021041915, it can not setting the ANC and Low Latency mode. I also use APP AB1562_UT ver 1.2.2.2020071618.

I want share this new firmware to all users, but I do not know what this model is, and I do not know how to dump the firmware.

By the way: I can not use Google Play Store , so can you send me a lastest AirReps APK ?

Some screenshot:
https://imgtu.com/i/4qiwUf
https://imgtu.com/i/4qiVgj

**Comment by wavpro** [comment]
Hello, sorry that I didn't reply in time, I never saw the issue. I don't work actively on this project anymore, but last I checked there is no good way to dump firmware from the model. Thank you for the interest though!
